### ISSUE TITLE
Tips for compiling against uclibc rather than musl?

### ISSUE THREAD

**Issue by elimisteve** [clux/muslrust#10]
I'm trying to compile Rust binaries against an OpenWRT-based MIPS system, and http://nitschinger.at/Rust-on-the-Wifi-Pineapple-and-OpenWRT/ isn't quite working for me, so being able to use something like `muslrust` but for uclibc rather than musl, would be great.

Any pointers on how to make that happen would be appreciated. Thanks!

**Comment by clux** [comment]
hm, i haven't really touched any ulibc or xargo so i don't really know how this is supposed to work.

looks like it's not one of the normal supported targets so you have jump through some hoops with xargo first? i'd try following his steps in a docker shell in ubuntu (say) and writing down what you need in a docker image format. Though if it's failing on yours it'll likely fail inside docker as well, but maybe worth retracing it again. It'll be easier for whoever you probably should be raising this with to debug a pushed docker image as well :D
