### ISSUE TITLE
Please rebuild "stable" less often or add a "LTS" version

### ISSUE THREAD

**Issue by KonradHoeffner** [clux/muslrust#102]
I use muslrust with cargo-chef to speed up Docker Rust builds with layer caching, however every day "stable" changes and it has to redownload the image and rebuild everything, which makes the cache less useful. I pin the version to clux/musrust:1.62.1-stable now, however this means I won't get security patches and so on.

Would it be possible to rebuild "stable" only when the version changes, or to provide an addtional more long term image that only changes let's say once a month?

**Comment by clux** [comment]
Yeah, that is a reasonable request. It's [actually what it's supposed to happen](https://github.com/clux/muslrust/blob/main/.github/workflows/stable.yml#L27-L33) but forgot about fixing this during the travis -> gha migration.

I'll try to debug it a bit later.

**Comment by clux** [comment]
Ok, after some frustration with GHA, I think this is fixed now, at least the conditions are respected. Hopefully it hasn't broken it too hard so the next stable doesn't get built, but I think we should be good now. Will detect that when the time comes. In the mean time, closing this :-)

**Comment by KonradHoeffner** [comment]
Can confirm, it works, thanks! On <https://hub.docker.com/r/clux/muslrust/tags>, stable was last updated 3 days ago.
