### ISSUE TITLE
What do you think about using tags like official Rust Docker image?

### ISSUE THREAD

**Issue by frederikhors** [clux/muslrust#103]
What do you think about using tags like official Rust Docker image?

rust:1 or rust:1.62 and so on?

**Comment by clux** [comment]
not super keen on it to be honest. we need to distinguish between nightly and stable, which [_/rust](https://hub.docker.com/_/rust?tab=description) doesn't. also it would be a breaking change.

if you want to minimize configuration management, i would just put `muslrust:stable`
