### ISSUE TITLE
feature request: add protoc into the image

### ISSUE THREAD

**Issue by Sherlock-Holo** [clux/muslrust#105]
`tonic-build` require the protoc cli tool to generate codes, this image doesn't contain this tool

**Comment by clux** [comment]
I think that's reasonable request as it's a very common dependency.

Will put this as help-wanted for now. Will need compile instructions from src in the `Dockerfile` and ideally a quick test crate.

**Comment by Sherlock-Holo** [comment]
I create a PR to add protoc https://github.com/clux/muslrust/pull/106
@clux

**Comment by Zizico2** [comment]
Is Tonic still working? I seem to need `protobuf-dev`.
I'm getting: `google/protobuf/any.proto: File not found`
