### ISSUE TITLE
What do you think about this anti-musl post?

### ISSUE THREAD

**Issue by frederikhors** [clux/muslrust#118]
What do you think about https://andygrove.io/2020/05/why-musl-extremely-slow/?

**Comment by frederikhors** [comment]
https://github.com/rust-lang/rust/issues/70108

**Comment by clux** [comment]
the article is a little old, and a bit unsubstantiated apart from that stray allocator issue that ripgrep has solved by using jemalloc. see https://github.com/BurntSushi/ripgrep/issues/1691#issuecomment-851719079 benchmarking and working around it by swapping allocators; they still use musl releases. there's a more recent discussion on reddit: https://www.reddit.com/r/rust/comments/oh2k8l/rust_musl_and_glibc_in_2021/ .

...that said, i kind of want to check performance here again. maybe should spin up a workloading tool and run with/without jemalloc and also compare against a more standard native amd64 build.

to clarify, there's definitely plenty of reasons not to want to use musl;

- potential performance hits (likely just allocator at this point)
- static linking makes software supply chain updates harder (you rely on me/build image bumping pins)
- static linking makes embedding SBOMs harder (and image scanners cannot find dependencies as easily, and often don't support static)
- static linking is pretty bad if you need extra processes in your image (embedded logger say, now you are probably shipping two tls stacks)

but philosophically, i hope these are things that will be overcome as time passes. the reduced code surface inside your image is great for security, and the smaller image size is a nice plus for local development, being able to ship a binary to all linux distros is killer, and the need for custom build images like this should drop once people stop pulling in C dependencies (soon openssl...). i think musl has can have real use long term provided the minor issues can be sorted out.

**Comment by clux** [comment]
Oh, this is promising and much more recent: https://users.rust-lang.org/t/optimizing-rust-binaries-observation-of-musl-versus-glibc-and-jemalloc-versus-system-alloc/8499/3

> In all the scenarios I've tried, musl-compiled Rust binaries are significantly faster than their glibc counterparts, so it's worth investigating this in your own projects. I've seen speedups ranging from 50% to 1000% faster.

**Comment by clux** [comment]
EDIT: this [2016* post](https://users.rust-lang.org/t/optimizing-rust-binaries-observation-of-musl-versus-glibc-and-jemalloc-versus-system-alloc/8499) i think got a lot of people interested in it. But needs more retesting now after years of changes.

**Comment by clux** [comment]
And this is probably a more substantive critique of musl performance issues: https://www.linkedin.com/pulse/testing-alternative-c-memory-allocators-pt-2-musl-mystery-gomes/

Definitely want to re-test things now...

**Comment by clux** [comment]
While researching some more; found some more good points on the benefits of musl in this podcasts:
> https://changelog.com/shipit/76
> Container base images with glibc & musl
featuring Ariadne Conill, Alpine Linux TSC member & Chainguard SWE

**Comment by frederikhors** [comment]
Very interesting everything. Thanks. I think I'll benchmark my apps in both way.
