### ISSUE TITLE
reduce image size by removing build dependencies

### ISSUE THREAD

**Issue by clux** [clux/muslrust#12]
E.g. use specific install scripts rather than having everything inlined in docker images, and have them keep track of build deps and remove them after compiling in one layer.

See how [cross does its musl install](https://github.com/japaric/cross/blob/master/docker/musl.sh). Their images are about half our size, so could save space here. That said, they are also not including rust properly because they are mounting toolchains, so how much remains to be seen.

If we do want to support other targets then this kind of thing would be instrumental for reducing duplication anyway though.

**Comment by corbinu** [comment]
@clux Just a note I think you can shrink it WAY more once this PR https://github.com/rust-lang/rust/pull/40113 lands as you should be able to base the image on Alpine

**Comment by clux** [comment]
Oooh, yeah that would be amazing. Then I don't even have to compile openssl, right? It's just there statically in the alpine packages.

**Comment by corbinu** [comment]
Yes pretty sure it is just `apk --no-cache add openssl-dev`

**Comment by Shizmob** [comment]
`libressl-dev`, actually. OpenSSL is only kept around for compatibility reasons and will conflict with other packages, most likely.

**Comment by corbinu** [comment]
@clux @Shizmob Correct me if I am wrong but since OpenSSL is getting built into the binary which version that Alpine uses is meaningless. What matters is which the developer wants build into their Rust Binary. (I would assume this means it could just be an ENV variable that you could pass to the docker container which decides which gets installed)

**Comment by Shizmob** [comment]
It depends if any of the other build dependencies (for Rust or otherwise) conflict - `openssl-dev` and `libressl-dev` can not be installed at the same time, so if a build dependency wants `libressl-dev`, `openssl-dev` is out of the question.

**Comment by corbinu** [comment]
@Shizmob Yes of course... obviously the opposite would also be true thats why I suggested it should be a flag on the container for which ends up installed.

**Comment by clux** [comment]
Going to not care about this particular issue for now. An alpine version of this would be nice, but for now, while we're on ubuntu, having build time dependencies is useful for crates that actually need to them as part of their build steps. Having cmake/autotools/make/libtool etc is a cheap price to pay to get all these crates working.
