### ISSUE TITLE
Pinning rust-nightly

### ISSUE THREAD

**Issue by sevagh** [clux/muslrust#14]
Hello,

I'm using this container as a base for a Rust build container within my org. I added a little feature to support pinned/fixed nightly versions:

In my `build.sh` to build the container:

```bash
docker build --no-cache --build-arg NIGHTLY_SNAPSHOT="2017-06-13" -t "${name}" -f ./Dockerfile.muslrust_improved .
```

In the Dockerfile:

```docker
ARG NIGHTLY_SNAPSHOT=""

RUN if test "${NIGHTLY_SNAPSHOT}"; then DATEARG="--date=${NIGHTLY_SNAPSHOT}"; fi &&\
  curl https://static.rust-lang.org/rustup.sh | sh -s -- \
  --with-target=x86_64-unknown-linux-musl \
  --yes \
  --disable-sudo \
  ${DATEARG}\
  --channel=nightly &&\
  mkdir /.cargo && \
  echo "[build]\ntarget = \"x86_64-unknown-linux-musl\"" > /.cargo/config
```

In short, if you add the appropriate build-arg, it'll pin that nightly version with the `--date` flag to `rustup.sh`. If not, it'll proceed like normal with the latest nightly.

Is this something interesting to push upstream? If it is, let me know and I'll make a pull request.

**Comment by clux** [comment]
Hey, thank you this is a pretty useful idea. Was considering making a rustup.rs branch so people could use new rustup properly inside the container, but that still forces CI people to have to `rustup update nightly-$NIGHTLY_SNAPSHOT` as part of the build process, which is slow.

This is probably a nicer solution, allowing people to make images later on themselves if there's not a built nightly for it on dockerhub - i'm not always right on the ball with pinging the travis builds.

Would be good to have some system so people could just request a specific nightly from the past with a PR here.

At any rate, I'd gladly take a PR and look at tinkering with it :+1:

**Comment by sevagh** [comment]
https://github.com/clux/muslrust/pull/15

**Comment by clux** [comment]
Thanks, that is useful. I've merged it.

I'll probably tweak that a bit over the coming days though, so I can use ARGs to build both stable and nightly without mucking around with branches firstly. But I can notify here when the `ARG`s  changes.

Thanks again.
