### ISSUE TITLE
Adding libpq?

### ISSUE THREAD

**Issue by freiguy1** [clux/muslrust#17]
Hello. I'm building a rest API which uses postgresql and Diesel. After finding this repo, I'm really excited to get a binary built with static linking so I can easily and quickly deploy it. However I'm inexperienced in the realm of compiling libraries like these from source. I wonder if this library would be worth adding, and if not, could you point me in the right direction so I can get started on a fork of your container.  I do see Alpine has libpq in their [package repository](https://pkgs.alpinelinux.org/package/edge/main/x86/libpq). Maybe the simplest way would be getting the binary from there?

**Comment by clux** [comment]
Hey, yeah libpq is definitely the kind of thing we'd want in here. Particularly with the usage numbers from diesel :)

Ideally we'd probably move this image to alpine entirely soon - at which point we can just use their package - but in the mean time you'd have to compile it here.  I'm a bit busy for a few days, so please have a go :)

It generally should be a case of adding a new line to the docker file where you curl the libpq source  tarball (looks like it's part of postgres), pipe it into the correct incantation of tar, calling ./configure with some minimal set of parameters (need ssl support at least, but we don't need all of postgres either), then `make && make install`. Everything else should be set in the container for that to work.

It'd be good to write a small test crate that at least uses diesel in a minimal way (just to test that we can link - don't need to actually connect to a db).

**Comment by freiguy1** [comment]
Wow thanks for all the information. I'm actually out for the weekend but I'll take a look when I get back!

**Comment by corbinu** [comment]
@clux I am trying to get rustc to build on alpine but not having much luck. As soon as I figure it out will submit a PR for the upgrade.

**Comment by freiguy1** [comment]
Alright, I'm giving a shot at building postgresql-libs.  So far I've curled and extracted the source from postgresql's ftp.  Now I'm trying to configure.  So far, my command is: `./configure --with-openssl --without-readline --without-zlib`. I added the last two args because `configure` suggested them after errors.  Now this is the error I'm getting:

```
checking for CRYPTO_new_ex_data in -lcrypto... no
configure: error: library 'crypto' is required for OpenSSL
```

How do I get around this one?

**Comment by freiguy1** [comment]
Ok, a couple good things:

1. I actually was able to get past that issue and get postgresql lib completely compiled!
2. When trying to compliek my project, it successfully compiles all dependencies.

And a bad thing: when it starts to compile my project, cargo/rustc chokes on the first line:

```
   Compiling league_db v0.1.0 (file:///volume/db)
error: /usr/lib/x86_64-linux-gnu/libc.so: invalid ELF header
 --> db/src/lib.rs:1:14
  |
1 | #[macro_use] extern crate diesel_codegen;
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `league_db`.

To learn more, run the command again with --verbose.
```

**Comment by clux** [comment]
hm, yeah, seems it's trying to use glibc rather than something like `/usr/lib/x86_64-linux-musl/libc.a`. Maybe this is a configuration error of a crate that needs evars, or maybe it's compiled wrong. Hard to tell. At any rate, maybe the documentation for [pq-sys](https://github.com/sgrif/pq-sys) is useful, they have some configurables.

**Comment by clux** [comment]
Hey, did you get anywhere further with this? Got a branch somewhere? :)

**Comment by freiguy1** [comment]
Yes! I was able to get the postgre lib compiled and installed, but I didn't get past that build issue in the last comment I had here unfortunately. I have actually switched deployment directions a bit however, and gone with pushing the rust web app to heroku using the rust buildpack. Can't hardly beast the deployment process of `git push heroku master`!

**Comment by clux** [comment]
Hehe, that's fair. Thanks for that push at least.

I have absorbed your work in a branch here to have a little bit more of a go :)

**Comment by clux** [comment]
libpq is added now, new build on the way. pq-sys linking does work (which is what the test does), however, full usage of diesel with `diesel_codegen` (in particular) fails. new issue for that incoming.
