### ISSUE TITLE
CI build strategy

### ISSUE THREAD

**Issue by clux** [clux/muslrust#2]
Currently the thing is pushed manually after I build, test it, then test some bigger things with it. This is fine for now as I want to rely on it.

But if tests were more expansive, could easily just gate a nightly push on whether the tests passed.
Docker build takes around 10 minutes anyway, so would be nicer to have travis actually do the push so there's more trust.

Once this musl support is in stable this becomes less of an issue as well.

**Comment by bencord0** [comment]
What needs to be done to give travis docker push rights?

**Comment by clux** [comment]
Oh, it's trivial to add. But may want a better safe guard than just the few tests passed, then run it daily. Maybe we can tag the docker image with the date or something while we need nightlies.

**Comment by clux** [comment]
Alright travis now tags and updates both latest and some autogenerated tag based on `rustc --version` and `date`.

Not doing the whole docker automated build thing as it was a pain to deal with and I can't run my tests before pushing. I'd rather know the latest tag passed the tests than to have it "verified by docker" as not pushed outside CI. Though that's just because I trust myself..

At any rate; 

- [latest travis build log](https://travis-ci.org/clux/muslrust/builds/117244892)
- [docker hub tag view](https://hub.docker.com/r/clux/muslrust/tags/)

**Comment by clux** [comment]
Side note: This probably isn't going to be a popular approach on docker's side (with me creating numerous images per docker-file), but at least it will allow me to pin an image to a date which is kind of useful for bisecting nightlies.
