### ISSUE TITLE
Mysql support?

### ISSUE THREAD

**Issue by MorganNesbitt** [clux/muslrust#23]
Is there any intent for this image to support static mysql builds (or some branch / version)?

It seems Postgres support is more standard (or at least fleshed out) after looking into diesel static linking. 
I've tried modifying golddranks to build mysql from scratch with musl but its been proving incredibly difficult.

**Comment by clux** [comment]
I wasn't planning on it to be honest, postgres is more standard, and already feel like I have enough large C libraries to maintain build flags for / update.

Feel free to fork away though, would be nice to see if it works / have something to point people at :-)
You may find xenial to be a better starting point, as you don't have to deal with relocation errors as much as on stretch.

**Comment by MorganNesbitt** [comment]
Make sense. I'll post back here if I can ever get it working.

**Comment by asaaki** [comment]
@MorganNesbitt have you done anything around it already?

**Comment by MorganNesbitt** [comment]
No. I did not get the chance to dedicate much time as I didn’t get real buy off from my work who I was attempting to fix this for. I wish you good luck if you are trying though!
