### ISSUE TITLE
Release a new image for libsyntax (syntex 0.31.0) changes

### ISSUE THREAD

**Issue by jimmycuadra** [clux/muslrust#3]
There were some changes to libsyntax in nightly Rust since the last build of the muslrust image on the Docker Hub. Code generation crates (e.g. dependencies of Serde) have been updated for these changes and no longer build on the version of Rust in the latest image. Can you trigger another build for the latest nightly? Thanks!

**Comment by clux** [comment]
Hey, sure. Just doing a stable 1.8.0 build now first, but should have a new nightly up shortly after that.

**Comment by clux** [comment]
`clux/muslrust:1.9.0-nightly-2016-04-14` is done. Thanks for the heads up :+1:
