### ISSUE TITLE
Installing `clippy`

### ISSUE THREAD

**Issue by idubrov** [clux/muslrust#37]
Is there any way I can install `rust-src` component on top of this image (which is required by `clippy`)?

This image doesn't include `rustup` (with which you can do `rustup component add rust-src`) and I cannot quite figure out what exactly I need to do to emulate `rustup comuonent add rust-src`.

**Comment by clux** [comment]
Oh, interesting, didn't know `clippy` required this now.

I think you need to grab the corresponding nightly tarball and extract it somewhere (similar to old `racer` setup).
Clippy install seems to require `SYSROOT=/path/to/rustc/sysroot cargo install clippy` without `rustup`.

**Comment by idubrov** [comment]
Ok, I was completely wrong about `rust-src`. The real cause was that clippy would be installed for `musl` target, which lacks librustc.

The correct way to install clippy on top of this image is:

```
CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu cargo install clippy
```

**Comment by clux** [comment]
Ah, thanks for the update. I'll make a note of it in the README for future people :-)
