### ISSUE TITLE
error: could not find `Cargo.toml` in `/volume` or any parent directory

### ISSUE THREAD

**Issue by manfredlotz** [clux/muslrust#43]
I'm not sure if the problem is between keyboard and chair.

Here is what I did:
 
 cargo new --bin statictest
 cd statictest
 docker pull clux/muslrust
 docker run -v $PWD:/volume -t clux/muslrust cargo build

The last command gives me:
  error: could not find `Cargo.toml` in `/volume` or any parent directory

What did I miss? Thank you.

**Comment by manfredlotz** [comment]
When I run  `bash` I get a prompt. Typing `ls` and nothing happens. 

So I did: `docker run -v $PWD:/volume -t clux/muslrust /bin/ls` and got

/bin/ls: cannot open directory '.': Permission denied

Then something rang in my mind: I'm running Fedora where SELinux is on.
As a workaround I turned it off: `sudo setenforce 0` and now things are working fine.

I have to check how to get it running properly when SELinux is on.

Thanks a lot for your help

**Comment by manfredlotz** [comment]
Aaah, I found the recommended solution:

To give a docker container access to a volume on an SELinux enabled host system the Z flag has to be added to the volume mount like this:
   `docker run -v $PWD:/volume:Z -t clux/muslrust  cargo build`

Perhaps you could add it to the documentation in the README.

**Comment by clux** [comment]
Seems reasonable, thanks. Linking previous fedora discussion in https://github.com/clux/muslrust/issues/6
