### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by manfredlotz** [clux/muslrust#44]
For my command line app I need a static libmagic in order to be able to build a static binary.

Do you add additional libraries upon request?  That would be great. On the other hand I understand if you think libmagic is too exotic.

**Comment by clux** [comment]
Hm, what crates require this? I've not come across this library.

Instinctively; not sure it's worth making a regular build image bigger for the smaller subset of people that want it though. Also, don't really want a bunch more C libraries in here unless they are genuinely useful in popular crates.

A solution could be to use the pattern by [portier-broker](https://github.com/portier/portier-broker/blob/master/Dockerfile) and extend muslrust to compile in your libmagic, i'll gladly link to that as a solution for extra libraries at the very least!

**Comment by manfredlotz** [comment]
Crate `magic` requires libmagic. 

The main problem I face is that I don't know exactly how to build a static libmagic. Somewhere I found file-5.34.tar.gz which contains the libmagic stuff.

**Comment by manfredlotz** [comment]
Just for the record. 

I managed to rewrite a limited version of libmagic in Rust so that I can now build a static library using muslrust. It was quite easy to do because I don't need to discriminate between different types of binaries, or archives aso.  Means, I get what I want by doing much less analyzing work than libmagic which makes my version much faster.
