### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by manfredlotz** [clux/muslrust#46]
When building a project using muslrust I get:

error[E0432]: unresolved import `core::ffi::c_void`
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.44/src/unix/mod.rs:1151:17
     |
1151 |         pub use core::ffi::c_void;
     |                 ^^^^^^^^^^^^^^^^^ no `c_void` in `ffi`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `libc`.

I ran: sudo docker run -v cargo-cache:/home/manfred/.cargo:Z -v "$PWD:/volume:Z" --rm -it clux/muslrust cargo build --release

I have a toy project https://gitlab.com/Lotz/beginning_nom where the error happens as well.

**Comment by manfredlotz** [comment]
Using muslrust:stable like follows:

` sudo docker run -v cargo-cache:/root/.cargo/registry:Z -v "$PWD:/volume:Z" --rm -it clux/muslrust:stable cargo build --release`

works fine.

Then running 
` sudo docker run -v cargo-cache:/root/.cargo/registry:Z -v "$PWD:/volume:Z" --rm -it clux/muslrust cargo build --release` I get the error I initially reported.

**Comment by manfredlotz** [comment]
I found this: https://users.rust-lang.org/t/failed-to-compile-new-crate-due-to-unfound-symbol-in-core-ffi/22930

Presumably related.

**Comment by clux** [comment]
Did you find out if this resolved itself on nightly?

**Comment by clux** [comment]
tested quickly with nom now and it works.
