### ISSUE TITLE
Suggest using `/root/.cargo` as the Docker volume

### ISSUE THREAD

**Issue by Aaron1011** [clux/muslrust#56]
Mounting the `cargo-cache` volume at `/root/.cargo/registry` excludes the `/root/.cargo/git` directory. This causes Cargo to re-fetch all Git dependencies on each build, which can be quite slow.

**Comment by clux** [comment]
That's a good catch, thank you. Will verify and update the docs.

**Comment by clux** [comment]
Unfortunately mounting `/root/.cargo` causes the container to complain that it cannot find the `cargo` binary (in `~/.cargo/bin/`), so the only sensible thing I can do here atm is to suggest mounting both directories.

**Comment by clux** [comment]
Going to close this for now. Re-open if people think there are reasonable actions. I don't see any atm.
