### ISSUE TITLE
Beta Image

### ISSUE THREAD

**Issue by glademiller** [clux/muslrust#60]
I was surprised to find you aren't publishing images for beta. I understand it is probably less used but it would have been useful in my particular case.

**Comment by clux** [comment]
I thought maybe at one point I would get around to this, but not heard a whole lot about more demand.

This repo also continues to be an unofficial best-effort helper image (with about average popularity) in a world of other musl builders, and with the updated docker hub usage limits, pushing daily nightly and stable images is already eating into my quota enough :(
