### ISSUE TITLE
make[1]: execvp: musl-ar: Permission denied

### ISSUE THREAD

**Issue by brainstorm** [clux/muslrust#67]
Great project @clux!

I'm getting the following with `:latest` on dockerhub:

```
(...)
musl-ar r apps/libapps.a apps/app_rand.o apps/apps.o apps/bf_prefix.o apps/opt.o apps/s_cb.o apps/s_socket.o
Makefile:677: recipe for target 'apps/libapps.a' failed
make[1]: Leaving directory '/target/debug/build/openssl-sys-c075376a27079383/out/openssl-build/build/src'
Makefile:177: recipe for target 'build_libs' failed

--- stderr
make[1]: execvp: musl-ar: Permission denied
make[1]: *** [apps/libapps.a] Error 127
make[1]: *** Waiting for unfinished jobs....
make: *** [build_libs] Error 2
thread 'main' panicked at '


Error building OpenSSL:
    Command: "make" "build_libs"
    Exit status: exit code: 2


    ', /cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.6.1+1.1.1d/src/lib.rs:365:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
```

**Comment by brainstorm** [comment]
Context: https://github.com/rust-bio/rust-htslib/pull/184/commits/0ca9400212385b673a11e015a2d6ff01ffec549d

**Comment by clux** [comment]
Uh, never seen that before. Looks like the C build script is trying to create c archives with `musl-ar` which I'm not sure is exposed or not. Don't have time to debug much, but would advise you try to shell into the docker image and debug why that isn't working.

**Comment by brainstorm** [comment]
Yeah, that happened because I was [vendoring openssl](https://github.com/rust-bio/rust-htslib/pull/184/commits/b10c48f21408f1df44d90f288809be1b81467635#diff-e10681a87641afaed793e8505284f9cfR34) so might have clashed badly with the container setup? There was no `musl-ar` binary to be found there... [getting other errors now](https://github.com/rust-bio/rust-htslib/pull/184#commitcomment-37496651), so closing this.
