### ISSUE TITLE
Push 1.43 stable image tag on dockerhub

### ISSUE THREAD

**Issue by kcking** [clux/muslrust#69]
Heyo, thank you for the awesome dockerimage! I use it for all of my hosted rust applications.

Could you please build and push the stable 1.43.0 image when you get a chance?

Thanks!

**Comment by clux** [comment]
Hey! It's on my TODO list. It's normally automatic, but the build is broken and haven't had the chance to debug yet.

**Comment by clux** [comment]
There, had time to sort it. `clux/muslrust:1.43.1-stable` now pushed.
