### ISSUE TITLE
automate the manual switchover for stable

### ISSUE THREAD

**Issue by clux** [clux/muslrust#71]
Currently, I make a few git actions to get travis to release a new stable image, but would like to be able to step away and not miss the patch releases.

We could automate this pretty easily if there is an API to get the latest stable rust release (just the version), I just haven't found it. If anyone know it would be very helpful!

**Comment by clux** [comment]
I tried doing a curl to github releases for rust-lang, but it kept giving me empty lists, so I gave up :|
Maybe I fsked it up though.

**Comment by AnderEnder** [comment]
@clux,
I have an draft idea:
* small cron task(every 4-8 hours?) which evaluates availability of new release using rustup dist manifest date: https://static.rust-lang.org/dist/channel-rust-stable.toml
* send `repository_dispatch event` to the repository
* run a build on repository_dispatch event

**Comment by clux** [comment]
Ooh. Yeah, that is promising. `pkg.rust.version` seems to have the latest stable in the middle of it, do you know if the file is reliably updated?

Might just try to make an extra daily travis-ci cronjobs (to avoid making more ci systems within this repo), and setup a stable branch to trigger it on.

**Comment by clux** [comment]
Quick toml parsing logic;

```py
def rust_stable_version():
    """Retrieve the latest rust stable version from static.rust-lang.org"""
    url = 'https://static.rust-lang.org/dist/channel-rust-stable.toml'
    req = urllib.urlopen(url)
    data = toml.loads(req.read().decode("utf-8"))
    req.close()
    return data['pkg']['rust']['version'].split()[0]
```

**Comment by clux** [comment]
Well, think there's a second travis cronjob now on the stable branch. Guess we'll see if this works on Thursday.

**Comment by AnderEnder** [comment]
My draft injected shell script:
https://github.com/AnderEnder/muslrust/blob/switch-to-github-actions/.github/workflows/cron.yml

`toml` manifest provides only date, but I get the last date-time from `last-modified` http header. It should be correct enough, because it was taken from s3 metadata.

I would like to test it and will provide the PR .

The manifest file is used by rustup, so it is the most reliable source.

**Comment by clux** [comment]
Just for closure, ended up taking your original draft idea above, and made it work (in parallel with your testing on github actions) on travis. Forgot to close and respond.Sorry.

Still, really appreciate you helping out here. Your idea made all the difference - even if it's still travis here.

Travis has worked really well for me for this repo; let me run these 8min jobs daily for years, free - so am happy to have gotten it  to a state where i could just keep it like that and leave it. The github action solution does looks really nice as well though. I'll probably look at that again that for any new repos I make.

At any rate, this is automatic here as well (as proved by 1.44.1), so closing.
