### ISSUE TITLE
Migrate travis account to new domain, builds ceased on travis-ci.org

### ISSUE THREAD

**Issue by tranzystorek-io** [clux/muslrust#78]
According to https://blog.travis-ci.com/2021-05-07-orgshutdown and the banner on the webpage, travis builds were ceased on June 15 and to bring them back, accounts need to be migrated to the new travis-ci.com domain.

This is consistent with the last image having been built on Monday, June 14.

**Comment by clux** [comment]
Thanks, I had forgotten about this :|
I'll have a go at github-actionizing this repo.

**Comment by clux** [comment]
Think I've got something working, although having some docker permission issues. Will close when the first new tag appears on dockerhub.

**Comment by clux** [comment]
New stable tags released on https://hub.docker.com/repository/docker/clux/muslrust/tags?page=1&ordering=last_updated for 1.53.0.

Expecting nighties to be uploaded soon.

**Comment by tranzystorek-io** [comment]
Nice, thanks for working on this!

**Comment by clux** [comment]
nightly builds passing and pushed - https://github.com/clux/muslrust/runs/2865744085?check_suite_focus=true
https://hub.docker.com/repository/docker/clux/muslrust/tags?page=1&ordering=last_updated

closing.
