### ISSUE TITLE
Fails to install wasm-pack 0.10

### ISSUE THREAD

**Issue by mverleg** [clux/muslrust#82]
(I don't know if this is related to wasm-pack or the image or both - please close if misplaced)

Doing this:

    FROM clux/muslrust:nightly-2021-07-02
    RUN cargo install wasm-pack --version 0.10.0

Fails with a lot of link errors:

    #5 93.85    Compiling wasm-pack v0.10.0
    #5 105.5 error: linking with `cc` failed: exit status: 1
    #5 105.5   |
    #5 105.5   = note: "cc" "-m64" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crt1.o" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown
    ...
    gc-sections" "-static" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crtend.o" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crtn.o"
    #5 105.5   = note: /tmp/cargo-installxuDjo0/x86_64-unknown-linux-musl/release/deps/libcurl_sys-bba798c182a3b3c5.rlib(s23_clnt.o): In function `ssl_fill_hello_random':
    #5 105.5           s23_clnt.c:(.text+0x60): multiple definition of `ssl_fill_hello_random'
    #5 105.5           /tmp/cargo-installxuDjo0/x86_64-unknown-linux-musl/release/deps/libopenssl_sys-9c5c29a7f29a1d71.rlib(s3_lib.o):s3_lib.c:(.text.ssl_fill_hello_random+0x0): first defined here
    #5 105.5           /tmp/cargo-installxuDjo0/x86_64-unknown-linux-musl/release/deps/libcurl_sys-bba798c182a3b3c5.rlib(t1_lib.o): In function `tls1_default_timeout':
    #5 105.5           t1_lib.c:(.text+0xa50): multiple definition of `tls1_default_timeout'
    #5 105.5           /tmp/cargo-installxuDjo0/x86_64-unknown-linux-musl/release/deps/libopenssl_sys-9c5c29a7f29a1d71.rlib(t1_lib.o):t1_lib.c:(.text.tls1_default_timeout+0x0): first defined here
    #5 105.5           /tmp/cargo-installxuDjo0/x86_64-unknown-linux-musl/release/deps/libcurl_sys-bba798c182a3b3c5.rlib(t1_

**Comment by clux** [comment]
looks like wasm-pack somewhere in its dependency tree pulls in ssl another way.

this seems confirmed by wasm-pack's vendored openssl feature: https://github.com/rustwasm/wasm-pack/blob/master/Cargo.toml#L48-L50

maybe try wasm-pack without default features?

**Comment by mverleg** [comment]
Oh that seems likely, trying it. Thanks for having a look!
