### ISSUE TITLE
openssl version

### ISSUE THREAD

**Issue by marlon-sousa** [clux/muslrust#85]
Hello,

By reading the docker file it seems openssl 1.1 is not supported. Is this the case?

I ask because on the README file this is not clear and this is an important information.

Thanks,
Marlon

**Comment by clux** [comment]
Yeah, that's correct. #9 did try to address this, but have not had time to look at it. We should update the documentation for it though.

**Comment by marlon-sousa** [comment]
Have you looked at https://github.com/emk/rust-musl-builder?

This is a kit similar project, although it doen't seem to be maintained anymore.

Perhaps it makes sense to use the same aproach they did to get openssl to compile.

**Comment by clux** [comment]
Ah, yeah, I think there's a lot of implicit sharing of ideas between these projects (i.e. `emk`, `golddranks`, mine) but must admin haven't been paying that much attention to it lately.

I think that would make sense to port that approach here. Might be a bit busy this week, but if you feel up for it, feel free to try to raise a PR.

**Comment by JonathanxD** [comment]
I think that this become more important as of today (30-sep-2021) given that [DST Root CA X3 expired](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) and it may cause troubles for produced binaries (I got "expired certificate" myself while building pijul using this image)

**Comment by clux** [comment]
@JonathanxD Thanks that's a good point. I have done a naive bump in the referenced pr #86 and pushed an image from that under [clux/muslrust:1.55.0-openssl11](https://hub.docker.com/layers/clux/muslrust/1.55.0-openssl11/images/sha256-3b1dcfbd781a3e36b51b34d603433dd49995d048cc96ec374e8c3fcc00b7a2fc?context=explore). My base tests are passing (e.g. linking works), but don't have DST cert expiry as part of test suite. Do you think you would be able to test it out?

**Comment by JonathanxD** [comment]
@clux Sure I can!! And it's working! I've been able to build pijul locally and clone the pijul repo itself, which wasn't working before (because of expired cert).
I'm now updating my CI/CD environment and it will solve the problem I was having.

Tks so much!!

**Comment by nlordell** [comment]
FWIW, we also use `muslrust` and were having issues with the expired DST certs. The `1.55.0-openssl11` image also fixed things for us.

**Comment by clux** [comment]
Awesome. Thanks all. I'll merge and get some releases out over the next couple of days.

**Comment by clux** [comment]
Ok, some few extra linking issues on the tests (hyper test is very out of date) so keeping this open until this is open for now and will try to fix it later.

**Comment by clux** [comment]
Ok, both builds ([nightly](https://github.com/clux/muslrust/runs/3775804999?check_suite_focus=true) and [stable](https://github.com/clux/muslrust/runs/3776288731?check_suite_focus=true))  have propagated [new tags to docker hub](https://hub.docker.com/r/clux/muslrust/tags?page=1&ordering=last_updated) with version `1.1.1i` of openssl. closing :sweat_smile:
