### ISSUE TITLE
Unable to build prost due to old version of cmake on ubuntu:xenial

### ISSUE THREAD

**Issue by luke-biel** [clux/muslrust#91]
Cmake-rs (https://github.com/rust-lang/cmake-rs/issues/131) and by dependency prost has recently bumped cmake dependency to `3.12` (with use of `--parallel` cmd line flag). As muslrust uses ubuntu 16.04, it's apt repositories only support downloading `3.5.1`.

An os version bump would be nice there.

**Comment by luke-biel** [comment]
There's no rush in this case, I wanted to inform about this because `cmake-rs` seems like dependency that is used by many crates.

Workaround in my case was to fetch the repo and manually change ubuntu to `jammy`. Build went fine and all crates compiled. It's weird, because we have `ring` in `Cargo.lock`. No `rocket` though, as servers run on `axum`.

**Comment by clux** [comment]
have upgraded today, new images are built with jammy.

admittedly this is a bit of a sharp break because we have no tagging scheme to distinguish between xenial andjammy, but hopefully it's something that's not too hard to work around.
